### ISSUE TITLE
Error building the frontend

### ISSUE THREAD

**Issue by tomislavkovacev** [directus-community/agency-os#39]
When running either `pnpm i` or `pnpm build` I am getting the following error (below).
this is happening both on a local install and also on netlify.
i am using the token from the admin user.

I'm not sure the `npx directus-template-cli@latest apply` command ran correctly.
I didn't get all the `Loaded - Roles` etc... only 2 of those came up, but i had about 10 or so `Applying Template - AgencyOS...` messages. Looks like all the tables have been created.

8:24:02 PM: Failed during stage "Install dependencies": dependency_installation script returned non-zero exit code: 1
8:24:01 PM: [start] Loading Directus Module
8:24:02 PM: [error] { errors:
8:24:02 PM:    [ { message: "You don"t have permission to access this.", extensions: [Object] } ],
8:24:02 PM:   response:
8:24:02 PM:    _Response [Response] {
8:24:02 PM:      [Symbol(realm)]: null,
8:24:02 PM:      [Symbol(state)]:
8:24:02 PM:       { aborted: false,
8:24:02 PM:         rangeRequested: false,
8:24:02 PM:         timingAllowPassed: true,
8:24:02 PM:         requestIncludesCredentials: true,
8:24:02 PM:         type: "default",
8:24:02 PM:         status: 403,
8:24:02 PM:         timingInfo: [Object],
8:24:02 PM:         cacheState: "",
8:24:02 PM:         statusText: "Forbidden",
8:24:02 PM:         headersList: [_HeadersList],
8:24:02 PM:         urlList: [Array],
8:24:02 PM:         body: [Object] },
8:24:02 PM:      [Symbol(headers)]:
8:24:02 PM:       _HeadersList {
8:24:02 PM:         cookies: [Array],
8:24:02 PM:         [Symbol(headers map)]: [Map],
8:24:02 PM:         [Symbol(headers map sorted)]: null } } }
8:24:02 PM: [error] undefined

**Comment by bryantgillespie** [comment]
hmm it must be running the Nuxt module on pnpm install.
But if you've set up your .env file correctly with the right URL and the right token it shouldn't be an issue.

**Comment by tomislavkovacev** [comment]
I think it must be to do with the initial setup of Directus I did, as mentioned I don’t feel it ran correctly.

I did try again from scratch about 4 times (locally) and was still getting the output I described.

 

If I check permissions against the roles should anything be setup that I can check for?

 

I generated a token for the admin user, which is in the admin group. Other then that are then any specific permissions I can check?

 

 

Thanks

Tommy.

**Comment by lucasshipsides** [comment]
what's the correct env var for the access token? i am getting the same error trying to deploy on fly and don't get prompted to enter it.

**Comment by bryantgillespie** [comment]
While I've heard of it, I'm not real familiar with Fly.io or how to deploy on the platform.

But the error you're receiving - looks like when you are trying to install dependencies in the Nuxt frontend. Nuxt runs a `prepare` command after pnpm install that apparently builds any modules and checks for errors.

If you look at the directus module, you'll see that it tries to fetch the redirects and globals from the Directus instance on build time.
https://github.com/directus-community/agency-os/blob/26c39ec13caa458e6b1bb6dc52cece4a005ff876/modules/directus/index.ts#L160C3-L190C82

The error is because your `DIRECTUS_URL` env var could be set incorrectly or some type of permissions issue on your Directus instance that's not allowing the module to access those collections.

**Comment by tomislavkovacev** [comment]
I now have it working locally by installing directus from the /.directus directory using the docker-compose.yaml file.
I did not install Directus this way originally.

Thankyou
