### ISSUE TITLE
passwordRequest not working in useDirectusAuth.ts?

### ISSUE THREAD

**Issue by Loosie94** [directus-community/agency-os#54]
Hi,

For a client project I use the AgencyOS template and so far I am really happy with it!
I have created a signup and login flow for users, and this is working great.

The only issue I am facing now, is that the `passwordRequest` doesn't seem to work.
I use the following script for this:

```
<script setup>
const { passwordRequest } = useDirectusAuth();
const loading = ref(false);
const error = ref(null);
const success = ref(false);

// Default client credentials
const credentials = reactive({
	email: localStorage.getItem('savedUsername') || '',
});

async function newPasswordRequest() {
	const { email } = unref(credentials);
	// const passwordResetUrl = 'http://localhost:3000/auth/reset-password';
	loading.value = true;
	error.value = null;

	try {
		await passwordRequest(email);
		success.value = true;
	} catch (err) {
		error.value = err.message;
	}

	loading.value = false;
}
</script>
```

This get triggered with a form submission, but then nothing happens.
Does this function exist in the AgencyOS template, and if not whats the easiest way to use this?
Thanks is advance!

**Comment by bryantgillespie** [comment]
So a few things.

1) We didn't build a resetPassword function inside the Nuxt frontend for this. You can see the [useDirectusAuth composable here](https://github.com/directus-community/agency-os/blob/main/modules/directus/runtime/composables/useDirectusAuth.ts) to see what's currently available - but basically just login, logout, and fetchUser.

But we should probably add one and the Directus REST API / SDK have support for it.
https://docs.directus.io/reference/authentication.html#request-password-reset

2) As far as how to achieve it yourself, I'd probably add a method for it within useDirectusAuth. And create a frontend route / page for it within the pages/auth directory.

One thing to make sure you set - if you plan on using the built-in Directus password resets, make sure to set the `PASSWORD_RESET_URL_ALLOW_LIST` variable within your Directus config. So you can redirect the user to the frontend instead of the Directus app.

Documentation here
https://docs.directus.io/self-hosted/config-options.html#security

![ScreenShot 2023-11-27 at 12 21 46@2x](https://github.com/directus-community/agency-os/assets/23302570/7c0ddd4a-553d-472e-bf98-aec51df1e4ee)

**Comment by Loosie94** [comment]
Hi @bryantgillespie 

I already did, I just forgot the `PASSWORD_RESET_URL_ALLOW_LIST` variable. My function is very simple, but works good. Code:

```
import { readMe, passwordRequest, passwordReset } from '@directus/sdk';
async function resetPassword(email: string, reset_url: string) {
		const response = await $directus.request(passwordRequest(email, reset_url));
	}
	```
	
Maybe good to add to this repo? I can probably make a pull-request later this week. 
Thanks! :)

**Comment by omgitsjan** [comment]
I'm working on something similar, how about the pull-request? That would save me some time @Loosie94  😄
